name: build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set lowercase username
        id: vars
        run: echo "username=${GITHUB_ACTOR,,}" >> $GITHUB_OUTPUT

      - name: log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build the Docker image
        run: docker build -t ghcr.io/${{ steps.vars.outputs.username }}/my-docker-app:latest .

      - name: push the Docker image
        run: docker push ghcr.io/${{ steps.vars.outputs.username }}/my-docker-app:latest
